server:
  port: 8888
spring:
  cloud:
    config:
       server:
         git:
           uri: https://gitee.com/ajax168/springCloudConfig/
           searchPaths: /
           username: ajax168
           password: 19841029zxc
       label: master
  application:
    name: config-server

eureka:
  client:
    service-url:
       defaultZone: http://ajax:123456@localhost:8080/eureka/
