server:
  port: 8080

spring:
  security:
    user:
      name: ajax
      password: 123456
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
      fetch-registry: false
      register-with-eureka: false
      service-url:
          defaultZone: http://localhost:8080/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000  #服务器清理间隔 默认 60 *1000 毫秒


