eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8088
spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /api/**
      serviceId: client