spring:
  application:
    name: client
  datasource:
    springdemo:
         driverClassName: com.mysql.cj.jdbc.Driver
         url: jdbc:mysql://127.0.0.1:3306/springdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT&allowMultiQueries=true&autoReconnect=true
         username: "root"
         password: ""
         # 下面为连接池的补充设置，应用到上面所有数据源中
         # 初始化大小，最小，最大
         initialSize: 5
         minIdle: 5
         maxActive: 30
         # 配置获取连接等待超时的时间
         maxWait: 60000
         # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
         timeBetweenEvictionRunsMillis: 60000
         # 配置一个连接在池中最小生存的时间，单位是毫秒
         minEvictableIdleTimeMillis: 30000
         validationQuery: select 'x'
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         # 打开PSCache，并且指定每个连接上PSCache的大小
         poolPreparedStatements: true
         maxPoolPreparedStatementPerConnectionSize: 20
         # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
         filters: stat,wall,slf4j
  cloud:
    config:
      label: master
      profile: dev
      name: cfg-dev
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://ajax:123456@localhost:8080/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30     # 续约更新时间间隔（默认30秒）
server:
  port: 8081
  compression:
      enabled: true
      min-response-size: 2048
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
  undertow:
    accesslog:
      enabled: true
      dir: D:\javaWork\SpringCloudDemo\client1\logs\
      pattern: "\"%{c,tranceId}\" \"%{i,versionCode}\" \"%{i,deviceId}\" %h %l %u %t \"%r\" %s %b \"%{i,Referer}\" \"%{i,user-Agent}\""
management:
  endpoints:
    web:
      exposure:
        include: refresh
mybatis:
  configuration:
    jdbc-type-for-null: 'null'