spring:
 application:
   name: client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3     # 续约更新时间间隔（默认30秒）
server:
  port: 8081
  compression:
      enabled: true
      min-response-size: 2048
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
  undertow:
    accesslog:
      enabled: true
      dir: D:\javaWork\SpringCloudDemo\client1\logs\
      pattern: "\"%{c,tranceId}\" \"%{i,versionCode}\" \"%{i,deviceId}\" %h %l %u %t \"%r\" %s %b \"%{i,Referer}\" \"%{i,user-Agent}\""
spring:
 cloud:
     config:
      label: master
      profile: dev
      name: cfg-dev
      discovery:
        enabled: true
        serviceId: config-server
